config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "messages#index"

  resources :users, only: [:edit, :update]
  namespace :admin do
    resources :registrations, only: [:new, :create, :destroy], path: 'sign_up'
    resources :sessions, only: [:new, :create, :destroy], path: 'sign_in'
    resources :companies, only: [:show] do
      resource :dashboard, only: [:show]
      resource :shared_password, only: [:new, :create, :edit, :update]
    end
  end

  resources :rooms, only: [:new, :create]

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :shared_password
  has_one :admin_user
  belongs_to :company, optional: true
  has_many :room_users
  has_many :rooms, through: :room_users

  enum role: { customer: 0, employee: 1 }

  with_options presence: true do
    validates :username, uniqueness: true
    validates :position
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'は10～11桁の半角数字でご入力ください' }

    with_options format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角文字でご入力ください' } do
      validates :last_name
      validates :first_name
    end
  end

  PASSWORD_REGEX = /\A(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}\z/
  validates :password, format: { with: PASSWORD_REGEX, message: 'は半角英数字混合かつ6字以上でご入力ください' }, if: -> { new_record? || !password.nil? }

  validate :check_shared_password, if: :employee?
  validate :check_company, if: :employee?

  def full_name
    "#{last_name} #{first_name}"
  end

  private

  def check_shared_password
    return if persisted? && !shared_password.present?

    if company.nil?
      errors.add(:company, "を入力してください")
      return
    end

    company_shared_password = company.shared_password
    
    is_valid = if company_shared_password
                 company_shared_password.authenticate(shared_password)
               else
                 SharedPassword.valid_initial_password?(shared_password)
               end

    errors.add(:shared_password, "が無効です") unless is_valid
  end

  def check_company
    errors.add(:company, "を入力してください") if company.blank?
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def create
    build_resource(sign_up_params.except(:company, :shared_password))

    if resource.employee?
      company_name = params[:user][:company]
      company = Company.find_or_create_by!(name: company_name)
      resource.company = company

      shared_password = params[:user][:shared_password]
      first_employee = company.users.employee.empty?

      if first_employee
        valid_password = SharedPassword.valid_initial_password?(shared_password)
      else
        valid_password = company.shared_password&.authenticate(shared_password)
      end

      unless valid_password
        resource.errors.add(:shared_password, "が無効です")
        return render :new, status: :unprocessable_entity
      end
    end

    resource.shared_password = shared_password
    resource.save
    yield resource if block_given?    #ブロックが与えられている場合、そのブロックを実行

    if resource.persisted?            #ユーザーオブジェクトがデータベースに保存されたかどうか
      if resource.active_for_authentication?  #ログイン可能な状態であるかどうか
        sign_up(resource_name, resource)

        if resource.employee? && first_employee
          redirect_to new_admin_registration_path, notice: '社内の最初の社員として登録されました。管理者アカウントを作成してください。'
        else
          respond_with resource, location: after_sign_up_path_for(resource)
        end

      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end

    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  protected

  def configure_sign_up_params
    keys = [:last_name, :first_name, :username, :position, :phone_number, :role]
    keys += [:company, :shared_password] if params[:user][:role] == 'employee'
    devise_parameter_sanitizer.permit(:sign_up, keys: keys)
  end

  def after_sign_up_path_for(resource)
    if resource.employee? && resource.company.users.employee.count == 1
      new_admin_registration_path
    else
      root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :position, :phone_number, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn'%>
      <%= link_to "Return to Chat-page", :back, class: 'btn'%>
      <% if current_user.admin_user.present? %>
        <%= link_to '>> 管理者専用ページはこちら', admin_company_dashboard_path(current_user.admin_user.company), class: 'sub-link' %>
      <% end %>
    </div>

    <div class='account-page__inner--right user-form'>
      <%= form_with model: @user, local: true do |f|%>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :username%>
          </div>
          <div class='field-input'>
            <%= f.text_field :username, autofocus: true%>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :position %>
            <i>[会社名・事業部名・役職名など]</i>
          </div>
          <div class='field-input'>
            <%= f.text_field :position%>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :phone_number %>
            <i>[ハイフンなし]</i>
          </div>
          <div class='field-input'>
            <%= f.text_field :phone_number, placeholder:"例）08012345678",maxlength:"11"%>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>

        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>

      <% end %>

    </div>
  </div>
</div>