config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "messages#index"

  resources :users, only: [:edit, :update]
  namespace :admin do
    resources :registrations, only: [:new, :create, :destroy], path: 'sign_up'
    resources :sessions, only: [:new, :create, :destroy], path: 'sign_in'
    resources :companies, only: [:show] do
      resource :dashboard, only: [:show]
      resource :shared_password, only: [:new, :create, :edit, :update]
    end
  end

  resources :rooms, only: [:new, :create]

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_company
  before_action :ensure_company_access!

  def show
    @admin_user = current_user.admin_user
    @shared_password = @company.shared_password
  end

  private

  def authenticate_admin_user!
    redirect_to root_path, alert: '管理者のみアクセス可能です' unless current_user&.admin_user
  end

  def set_company
    @company = current_user.admin_user.company
  end

  def ensure_company_access!
    company = Company.find_by(id: params[:company_id])
    if company.nil? || company != @company
      redirect_to admin_company_dashboard_path(@company), alert: 'アクセス権限がありません'
    end
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/show.html.erb
<div class='admin-account-page' id='admin-account-page'>
  <div class='admin-account-page__inner clearfix'>
    <div class='admin-account-page__inner--left admin-account-page__header'>
      <h2>Admin page</h2>
      <h5>管理者専用ページ</h5>
      <%= link_to "Link to Chat-page", root_path, class: 'btn'%><br>
      <%= link_to "Edit Company-Password", edit_admin_company_shared_password_path(@company), class: 'btn'%>
      <a href="#" class="btn">Change Admin-User</a>
    </div>

    <div class='admin-account-page__inner--right dashboard'>

      <div class='dashboard-field'>
        <div class='dashboard-label'>
          <h4>会社名</h4>
        </div>
        <div class='dashboard-content'>
          <p><%= @company.name %></p>
        </div>
      </div>

      <div class='dashboard-field'>
        <div class='dashboard-label'>
          <h4>管理者情報</h4>
        </div>
        <div class='dashboard-content'>
          <p>名前： <%= @admin_user.full_name %></p>
          <p>電話番号： <%= @admin_user.phone_number %></p>
          <p>メールアドレス： <%= @admin_user.email %></p>
        </div>
      </div>

      <div class='dashboard-field'>
        <div class='dashboard-label'>
          <h4>社内共通パスワード情報</h4>
        </div>
        <div class='dashboard-content'>
          <p>最終更新日： <%= @shared_password.updated_at.strftime('%Y年%m月%d日 %H:%M') %></p>
        </div>
      </div>

    </div>
  
  </div>
</div>